### ISSUE TITLE
When editing the game, the cancel button should be called delete

### ISSUE THREAD

**Issue by JuulArthur** [magination/Magination-Game-Site#17]
Even though there is a good message for when cancel is pressed, I feel user would feel more safe with this button called delete. As it not only cancels the editing but deletes the game as well

**Comment by LinkedT** [comment]
And it should pop-up to ask you "Do you want to delete this game? This action can't be reversed." (yes/no)

**Comment by PetterIve** [comment]
70269eac167a558e1b447e2f31727e7f238f0cbb
