### ISSUE TITLE
Attempting to create game while not logged in shows create site in background

### ISSUE THREAD

**Issue by hanskhe** [magination/Magination-Game-Site#29]
Clicking create from the front page without being logged in produces the result shown below.

![screen shot 2016-05-14 at 13 37 10](https://cloud.githubusercontent.com/assets/1413264/15268258/1953fb44-19d9-11e6-8eab-ca7f59b41cdf.png)

Should probably just show the modal?

**Comment by PetterIve** [comment]
As of now this is intentional.
