### ISSUE TITLE
Registering a new user with password length less then 7 gives no error on frontend.

### ISSUE THREAD

**Issue by lorang92** [magination/Magination-Game-Site#3]
Registering a new user with password length less then 7 gives no error on frontend.

**Comment by JuulArthur** [comment]
Experienced the same thing, only error message is the one received in the console. Should be a restriction for this frontend, so it is not possible to press sign up without passwords that are long enough

**Comment by PetterIve** [comment]
4c154909a30371b7d787d226a72d0478e6f71d24
